const challenge = [
  {
    image: "/code.visualstudio.com_.png",
    assets: [],
  },
  {
    image: "/code.visualstudio.com_.png",
    assets: [],
  },
  {
    image: "/discord.com_.png",
    assets: [],
  },
  { image: "/duckduckgo.com_.png", assets: [] },
  { image: "/getbootstrap.com_.png", assets: [] },
  { image: "/github.com_.png", assets: [] },
  { image: "/go.dev_.png", assets: [] },
  { image: "/medium.com_.png", assets: [] },
  { image: "/slack.com_.png", assets: [] },
  { image: "/stripe.com_.png", assets: [] },
  { image: "/unpigeon.me_.png", assets: [] },
  { image: "/www.aa.com_homePage.do.png", assets: [] },
  { image: "/www.android.com_.png", assets: [] },
  { image: "/www.apple.com_.png", assets: [] },
  { image: "/www.arduino.cc_.png", assets: [] },
  { image: "/www.delta.com_.png", assets: [] },
  { image: "/www.doordash.com_.png", assets: [] },
  { image: "/www.facebook.com_.png", assets: [] },
  { image: "/www.figma.com_.png", assets: [] },
  { image: "/www.google.com_.png", assets: [] },
  { image: "/www.lyft.com_.png", assets: [] },
  { image: "/www.netflix.com_.png", assets: [] },
  { image: "/www.notion.so_.png", assets: [] },
  { image: "/www.particle.io_.png", assets: [] },
  { image: "/www.php.net_.png", assets: [] },
  { image: "/www.postman.com_.png", assets: [] },
  { image: "/www.python.org_.png", assets: [] },
  { image: "/www.raspberrypi.org_.png", assets: [] },
  { image: "/www.rust-lang.org_.png", assets: [] },
  { image: "/www.spotify.com_.png", assets: [] },
  { image: "/www.united.com_.png", assets: [] },
  { image: "/www.usc.edu_.png", assets: [] },
];

module.exports = challenge;
